// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package dbqueries

import (
	"context"
)

const checkCompanyExists = `-- name: CheckCompanyExists :one
SELECT COUNT(*) as count
FROM companies
WHERE user_id = ? AND is_deleted = 0
`

func (q *Queries) CheckCompanyExists(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCompanyExists, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, user_id, name, money, created_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, user_id, name, money, created_at, is_deleted, deleted_at
`

type CreateCompanyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Money  int64  `json:"money"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Money,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Money,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, user_id, name, money, created_at, is_deleted, deleted_at
FROM companies
WHERE id = ? AND is_deleted = 0
`

func (q *Queries) GetCompanyByID(ctx context.Context, id string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Money,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyByUserID = `-- name: GetCompanyByUserID :one
SELECT id, user_id, name, money, created_at, is_deleted, deleted_at
FROM companies
WHERE user_id = ? AND is_deleted = 0
`

func (q *Queries) GetCompanyByUserID(ctx context.Context, userID string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByUserID, userID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Money,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCompany = `-- name: SoftDeleteCompany :exec
UPDATE companies
SET is_deleted = 1, deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteCompany(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteCompany, id)
	return err
}

const updateCompanyMoney = `-- name: UpdateCompanyMoney :one
UPDATE companies
SET money = ?
WHERE id = ? AND is_deleted = 0
RETURNING id, user_id, name, money, created_at, is_deleted, deleted_at
`

type UpdateCompanyMoneyParams struct {
	Money int64  `json:"money"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateCompanyMoney(ctx context.Context, arg UpdateCompanyMoneyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyMoney, arg.Money, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Money,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const updateCompanyName = `-- name: UpdateCompanyName :one
UPDATE companies
SET name = ?
WHERE id = ? AND is_deleted = 0
RETURNING id, user_id, name, money, created_at, is_deleted, deleted_at
`

type UpdateCompanyNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateCompanyName(ctx context.Context, arg UpdateCompanyNameParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyName, arg.Name, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Money,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}
