// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package dbqueries

import (
	"context"
)

const addToInventory = `-- name: AddToInventory :one
INSERT INTO company_inventory (id, company_id, resource_id, quantity)
VALUES (?, ?, ?, ?)
ON CONFLICT(company_id, resource_id) DO UPDATE SET
  quantity = quantity + excluded.quantity,
  is_deleted = 0,
  deleted_at = NULL
RETURNING id, company_id, resource_id, quantity, is_deleted, deleted_at
`

type AddToInventoryParams struct {
	ID         string `json:"id"`
	CompanyID  string `json:"company_id"`
	ResourceID string `json:"resource_id"`
	Quantity   int64  `json:"quantity"`
}

func (q *Queries) AddToInventory(ctx context.Context, arg AddToInventoryParams) (CompanyInventory, error) {
	row := q.db.QueryRowContext(ctx, addToInventory,
		arg.ID,
		arg.CompanyID,
		arg.ResourceID,
		arg.Quantity,
	)
	var i CompanyInventory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResourceID,
		&i.Quantity,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO company_inventory (id, company_id, resource_id, quantity)
VALUES (?, ?, ?, ?)
RETURNING id, company_id, resource_id, quantity, is_deleted, deleted_at
`

type CreateInventoryItemParams struct {
	ID         string `json:"id"`
	CompanyID  string `json:"company_id"`
	ResourceID string `json:"resource_id"`
	Quantity   int64  `json:"quantity"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (CompanyInventory, error) {
	row := q.db.QueryRowContext(ctx, createInventoryItem,
		arg.ID,
		arg.CompanyID,
		arg.ResourceID,
		arg.Quantity,
	)
	var i CompanyInventory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResourceID,
		&i.Quantity,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getInventoryByCompanyID = `-- name: GetInventoryByCompanyID :many
SELECT id, company_id, resource_id, quantity, is_deleted, deleted_at
FROM company_inventory
WHERE company_id = ? AND is_deleted = 0
ORDER BY resource_id
`

func (q *Queries) GetInventoryByCompanyID(ctx context.Context, companyID string) ([]CompanyInventory, error) {
	rows, err := q.db.QueryContext(ctx, getInventoryByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyInventory
	for rows.Next() {
		var i CompanyInventory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ResourceID,
			&i.Quantity,
			&i.IsDeleted,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, company_id, resource_id, quantity, is_deleted, deleted_at
FROM company_inventory
WHERE company_id = ? AND resource_id = ? AND is_deleted = 0
`

type GetInventoryItemParams struct {
	CompanyID  string `json:"company_id"`
	ResourceID string `json:"resource_id"`
}

func (q *Queries) GetInventoryItem(ctx context.Context, arg GetInventoryItemParams) (CompanyInventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItem, arg.CompanyID, arg.ResourceID)
	var i CompanyInventory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResourceID,
		&i.Quantity,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const removeFromInventory = `-- name: RemoveFromInventory :one
UPDATE company_inventory
SET quantity = ?
WHERE company_id = ? AND resource_id = ? AND is_deleted = 0
RETURNING id, company_id, resource_id, quantity, is_deleted, deleted_at
`

type RemoveFromInventoryParams struct {
	Quantity   int64  `json:"quantity"`
	CompanyID  string `json:"company_id"`
	ResourceID string `json:"resource_id"`
}

func (q *Queries) RemoveFromInventory(ctx context.Context, arg RemoveFromInventoryParams) (CompanyInventory, error) {
	row := q.db.QueryRowContext(ctx, removeFromInventory, arg.Quantity, arg.CompanyID, arg.ResourceID)
	var i CompanyInventory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResourceID,
		&i.Quantity,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const updateInventoryQuantity = `-- name: UpdateInventoryQuantity :one
UPDATE company_inventory
SET quantity = ?
WHERE id = ? AND is_deleted = 0
RETURNING id, company_id, resource_id, quantity, is_deleted, deleted_at
`

type UpdateInventoryQuantityParams struct {
	Quantity int64  `json:"quantity"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) (CompanyInventory, error) {
	row := q.db.QueryRowContext(ctx, updateInventoryQuantity, arg.Quantity, arg.ID)
	var i CompanyInventory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResourceID,
		&i.Quantity,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const upsertInventoryItem = `-- name: UpsertInventoryItem :one
INSERT INTO company_inventory (id, company_id, resource_id, quantity)
VALUES (?, ?, ?, ?)
ON CONFLICT(company_id, resource_id) DO UPDATE SET
  quantity = excluded.quantity,
  is_deleted = 0,
  deleted_at = NULL
RETURNING id, company_id, resource_id, quantity, is_deleted, deleted_at
`

type UpsertInventoryItemParams struct {
	ID         string `json:"id"`
	CompanyID  string `json:"company_id"`
	ResourceID string `json:"resource_id"`
	Quantity   int64  `json:"quantity"`
}

func (q *Queries) UpsertInventoryItem(ctx context.Context, arg UpsertInventoryItemParams) (CompanyInventory, error) {
	row := q.db.QueryRowContext(ctx, upsertInventoryItem,
		arg.ID,
		arg.CompanyID,
		arg.ResourceID,
		arg.Quantity,
	)
	var i CompanyInventory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResourceID,
		&i.Quantity,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}
