// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: production.sql

package dbqueries

import (
	"context"
)

const createProductionBuilding = `-- name: CreateProductionBuilding :exec
INSERT INTO production_buildings (id, master_id, name, construction_cost, construction_time_s)
VALUES (?, ?, ?, ?, ?)
`

type CreateProductionBuildingParams struct {
	ID                string `json:"id"`
	MasterID          string `json:"master_id"`
	Name              string `json:"name"`
	ConstructionCost  int64  `json:"construction_cost"`
	ConstructionTimeS int64  `json:"construction_time_s"`
}

// Production Buildings queries
func (q *Queries) CreateProductionBuilding(ctx context.Context, arg CreateProductionBuildingParams) error {
	_, err := q.db.ExecContext(ctx, createProductionBuilding,
		arg.ID,
		arg.MasterID,
		arg.Name,
		arg.ConstructionCost,
		arg.ConstructionTimeS,
	)
	return err
}

const createProductionProcess = `-- name: CreateProductionProcess :exec
INSERT INTO production_processes (id, master_id, production_building_id, name, cycle_time_s, window_start_hour, window_end_hour)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProductionProcessParams struct {
	ID                   string `json:"id"`
	MasterID             string `json:"master_id"`
	ProductionBuildingID string `json:"production_building_id"`
	Name                 string `json:"name"`
	CycleTimeS           int64  `json:"cycle_time_s"`
	WindowStartHour      *int64 `json:"window_start_hour"`
	WindowEndHour        *int64 `json:"window_end_hour"`
}

// Production Processes queries
func (q *Queries) CreateProductionProcess(ctx context.Context, arg CreateProductionProcessParams) error {
	_, err := q.db.ExecContext(ctx, createProductionProcess,
		arg.ID,
		arg.MasterID,
		arg.ProductionBuildingID,
		arg.Name,
		arg.CycleTimeS,
		arg.WindowStartHour,
		arg.WindowEndHour,
	)
	return err
}

const createProductionProcessResource = `-- name: CreateProductionProcessResource :exec
INSERT INTO production_process_resources (process_id, resource_id, is_output, quantity)
VALUES (?, ?, ?, ?)
`

type CreateProductionProcessResourceParams struct {
	ProcessID  string `json:"process_id"`
	ResourceID string `json:"resource_id"`
	IsOutput   bool   `json:"is_output"`
	Quantity   int64  `json:"quantity"`
}

// Production Process Resources queries
func (q *Queries) CreateProductionProcessResource(ctx context.Context, arg CreateProductionProcessResourceParams) error {
	_, err := q.db.ExecContext(ctx, createProductionProcessResource,
		arg.ProcessID,
		arg.ResourceID,
		arg.IsOutput,
		arg.Quantity,
	)
	return err
}

const deleteProductionProcessResources = `-- name: DeleteProductionProcessResources :exec
DELETE FROM production_process_resources
WHERE process_id = ?
`

func (q *Queries) DeleteProductionProcessResources(ctx context.Context, processID string) error {
	_, err := q.db.ExecContext(ctx, deleteProductionProcessResources, processID)
	return err
}

const getAllProductionBuildings = `-- name: GetAllProductionBuildings :many
SELECT id, master_id, name, construction_cost, construction_time_s
FROM production_buildings
ORDER BY name
`

func (q *Queries) GetAllProductionBuildings(ctx context.Context) ([]ProductionBuilding, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductionBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductionBuilding
	for rows.Next() {
		var i ProductionBuilding
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.Name,
			&i.ConstructionCost,
			&i.ConstructionTimeS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionBuildingByID = `-- name: GetProductionBuildingByID :one
SELECT id, master_id, name, construction_cost, construction_time_s
FROM production_buildings
WHERE id = ?
`

func (q *Queries) GetProductionBuildingByID(ctx context.Context, id string) (ProductionBuilding, error) {
	row := q.db.QueryRowContext(ctx, getProductionBuildingByID, id)
	var i ProductionBuilding
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.ConstructionCost,
		&i.ConstructionTimeS,
	)
	return i, err
}

const getProductionBuildingByMasterID = `-- name: GetProductionBuildingByMasterID :one
SELECT id, master_id, name, construction_cost, construction_time_s
FROM production_buildings
WHERE master_id = ?
`

func (q *Queries) GetProductionBuildingByMasterID(ctx context.Context, masterID string) (ProductionBuilding, error) {
	row := q.db.QueryRowContext(ctx, getProductionBuildingByMasterID, masterID)
	var i ProductionBuilding
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.ConstructionCost,
		&i.ConstructionTimeS,
	)
	return i, err
}

const getProductionProcessByID = `-- name: GetProductionProcessByID :one
SELECT id, master_id, production_building_id, name, cycle_time_s, window_start_hour, window_end_hour
FROM production_processes
WHERE id = ?
`

func (q *Queries) GetProductionProcessByID(ctx context.Context, id string) (ProductionProcess, error) {
	row := q.db.QueryRowContext(ctx, getProductionProcessByID, id)
	var i ProductionProcess
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.ProductionBuildingID,
		&i.Name,
		&i.CycleTimeS,
		&i.WindowStartHour,
		&i.WindowEndHour,
	)
	return i, err
}

const getProductionProcessByMasterID = `-- name: GetProductionProcessByMasterID :one
SELECT id, master_id, production_building_id, name, cycle_time_s, window_start_hour, window_end_hour
FROM production_processes
WHERE master_id = ?
`

func (q *Queries) GetProductionProcessByMasterID(ctx context.Context, masterID string) (ProductionProcess, error) {
	row := q.db.QueryRowContext(ctx, getProductionProcessByMasterID, masterID)
	var i ProductionProcess
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.ProductionBuildingID,
		&i.Name,
		&i.CycleTimeS,
		&i.WindowStartHour,
		&i.WindowEndHour,
	)
	return i, err
}

const getProductionProcessResources = `-- name: GetProductionProcessResources :many
SELECT process_id, resource_id, is_output, quantity
FROM production_process_resources
WHERE process_id = ?
ORDER BY is_output DESC, resource_id
`

func (q *Queries) GetProductionProcessResources(ctx context.Context, processID string) ([]ProductionProcessResource, error) {
	rows, err := q.db.QueryContext(ctx, getProductionProcessResources, processID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductionProcessResource
	for rows.Next() {
		var i ProductionProcessResource
		if err := rows.Scan(
			&i.ProcessID,
			&i.ResourceID,
			&i.IsOutput,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionProcessesByBuildingID = `-- name: GetProductionProcessesByBuildingID :many
SELECT id, master_id, production_building_id, name, cycle_time_s, window_start_hour, window_end_hour
FROM production_processes
WHERE production_building_id = ?
ORDER BY name
`

func (q *Queries) GetProductionProcessesByBuildingID(ctx context.Context, productionBuildingID string) ([]ProductionProcess, error) {
	rows, err := q.db.QueryContext(ctx, getProductionProcessesByBuildingID, productionBuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductionProcess
	for rows.Next() {
		var i ProductionProcess
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.ProductionBuildingID,
			&i.Name,
			&i.CycleTimeS,
			&i.WindowStartHour,
			&i.WindowEndHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductionBuilding = `-- name: UpsertProductionBuilding :exec
INSERT INTO production_buildings (id, master_id, name, construction_cost, construction_time_s)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(master_id) DO UPDATE SET
  id = excluded.id,
  name = excluded.name,
  construction_cost = excluded.construction_cost,
  construction_time_s = excluded.construction_time_s
`

type UpsertProductionBuildingParams struct {
	ID                string `json:"id"`
	MasterID          string `json:"master_id"`
	Name              string `json:"name"`
	ConstructionCost  int64  `json:"construction_cost"`
	ConstructionTimeS int64  `json:"construction_time_s"`
}

func (q *Queries) UpsertProductionBuilding(ctx context.Context, arg UpsertProductionBuildingParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductionBuilding,
		arg.ID,
		arg.MasterID,
		arg.Name,
		arg.ConstructionCost,
		arg.ConstructionTimeS,
	)
	return err
}

const upsertProductionProcess = `-- name: UpsertProductionProcess :exec
INSERT INTO production_processes (id, master_id, production_building_id, name, cycle_time_s, window_start_hour, window_end_hour)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(master_id) DO UPDATE SET
  id = excluded.id,
  production_building_id = excluded.production_building_id,
  name = excluded.name,
  cycle_time_s = excluded.cycle_time_s,
  window_start_hour = excluded.window_start_hour,
  window_end_hour = excluded.window_end_hour
`

type UpsertProductionProcessParams struct {
	ID                   string `json:"id"`
	MasterID             string `json:"master_id"`
	ProductionBuildingID string `json:"production_building_id"`
	Name                 string `json:"name"`
	CycleTimeS           int64  `json:"cycle_time_s"`
	WindowStartHour      *int64 `json:"window_start_hour"`
	WindowEndHour        *int64 `json:"window_end_hour"`
}

func (q *Queries) UpsertProductionProcess(ctx context.Context, arg UpsertProductionProcessParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductionProcess,
		arg.ID,
		arg.MasterID,
		arg.ProductionBuildingID,
		arg.Name,
		arg.CycleTimeS,
		arg.WindowStartHour,
		arg.WindowEndHour,
	)
	return err
}
