// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package dbqueries

import (
	"context"
)

const createResource = `-- name: CreateResource :exec
INSERT INTO resources (id, master_id, name, market_price, market_sale_qty)
VALUES (?, ?, ?, ?, ?)
`

type CreateResourceParams struct {
	ID            string `json:"id"`
	MasterID      string `json:"master_id"`
	Name          string `json:"name"`
	MarketPrice   int64  `json:"market_price"`
	MarketSaleQty int64  `json:"market_sale_qty"`
}

// Resources queries
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.ExecContext(ctx, createResource,
		arg.ID,
		arg.MasterID,
		arg.Name,
		arg.MarketPrice,
		arg.MarketSaleQty,
	)
	return err
}

const getAllResources = `-- name: GetAllResources :many
SELECT id, master_id, name, market_price, market_sale_qty
FROM resources
ORDER BY name
`

func (q *Queries) GetAllResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getAllResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.Name,
			&i.MarketPrice,
			&i.MarketSaleQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, master_id, name, market_price, market_sale_qty
FROM resources
WHERE id = ?
`

func (q *Queries) GetResourceByID(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResourceByID, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.MarketPrice,
		&i.MarketSaleQty,
	)
	return i, err
}

const getResourceByMasterID = `-- name: GetResourceByMasterID :one
SELECT id, master_id, name, market_price, market_sale_qty
FROM resources
WHERE master_id = ?
`

func (q *Queries) GetResourceByMasterID(ctx context.Context, masterID string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResourceByMasterID, masterID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.MarketPrice,
		&i.MarketSaleQty,
	)
	return i, err
}

const upsertResource = `-- name: UpsertResource :exec
INSERT INTO resources (id, master_id, name, market_price, market_sale_qty)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(master_id) DO UPDATE SET
  id = excluded.id,
  name = excluded.name,
  market_price = excluded.market_price,
  market_sale_qty = excluded.market_sale_qty
`

type UpsertResourceParams struct {
	ID            string `json:"id"`
	MasterID      string `json:"master_id"`
	Name          string `json:"name"`
	MarketPrice   int64  `json:"market_price"`
	MarketSaleQty int64  `json:"market_sale_qty"`
}

func (q *Queries) UpsertResource(ctx context.Context, arg UpsertResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertResource,
		arg.ID,
		arg.MasterID,
		arg.Name,
		arg.MarketPrice,
		arg.MarketSaleQty,
	)
	return err
}
