// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sale.sql

package dbqueries

import (
	"context"
)

const createSaleBuilding = `-- name: CreateSaleBuilding :exec
INSERT INTO sale_buildings (id, master_id, name, construction_cost, construction_time_s)
VALUES (?, ?, ?, ?, ?)
`

type CreateSaleBuildingParams struct {
	ID                string `json:"id"`
	MasterID          string `json:"master_id"`
	Name              string `json:"name"`
	ConstructionCost  int64  `json:"construction_cost"`
	ConstructionTimeS int64  `json:"construction_time_s"`
}

// Sale Buildings queries
func (q *Queries) CreateSaleBuilding(ctx context.Context, arg CreateSaleBuildingParams) error {
	_, err := q.db.ExecContext(ctx, createSaleBuilding,
		arg.ID,
		arg.MasterID,
		arg.Name,
		arg.ConstructionCost,
		arg.ConstructionTimeS,
	)
	return err
}

const createSaleResource = `-- name: CreateSaleResource :exec
INSERT INTO sale_resources (sale_building_id, resource_id, price_per_unit, units_sold_per_second)
VALUES (?, ?, ?, ?)
`

type CreateSaleResourceParams struct {
	SaleBuildingID     string `json:"sale_building_id"`
	ResourceID         string `json:"resource_id"`
	PricePerUnit       int64  `json:"price_per_unit"`
	UnitsSoldPerSecond int64  `json:"units_sold_per_second"`
}

// Sale Resources queries
func (q *Queries) CreateSaleResource(ctx context.Context, arg CreateSaleResourceParams) error {
	_, err := q.db.ExecContext(ctx, createSaleResource,
		arg.SaleBuildingID,
		arg.ResourceID,
		arg.PricePerUnit,
		arg.UnitsSoldPerSecond,
	)
	return err
}

const deleteSaleResources = `-- name: DeleteSaleResources :exec
DELETE FROM sale_resources
WHERE sale_building_id = ?
`

func (q *Queries) DeleteSaleResources(ctx context.Context, saleBuildingID string) error {
	_, err := q.db.ExecContext(ctx, deleteSaleResources, saleBuildingID)
	return err
}

const getAllSaleBuildings = `-- name: GetAllSaleBuildings :many
SELECT id, master_id, name, construction_cost, construction_time_s
FROM sale_buildings
ORDER BY name
`

func (q *Queries) GetAllSaleBuildings(ctx context.Context) ([]SaleBuilding, error) {
	rows, err := q.db.QueryContext(ctx, getAllSaleBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleBuilding
	for rows.Next() {
		var i SaleBuilding
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.Name,
			&i.ConstructionCost,
			&i.ConstructionTimeS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSaleBuildingByID = `-- name: GetSaleBuildingByID :one
SELECT id, master_id, name, construction_cost, construction_time_s
FROM sale_buildings
WHERE id = ?
`

func (q *Queries) GetSaleBuildingByID(ctx context.Context, id string) (SaleBuilding, error) {
	row := q.db.QueryRowContext(ctx, getSaleBuildingByID, id)
	var i SaleBuilding
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.ConstructionCost,
		&i.ConstructionTimeS,
	)
	return i, err
}

const getSaleBuildingByMasterID = `-- name: GetSaleBuildingByMasterID :one
SELECT id, master_id, name, construction_cost, construction_time_s
FROM sale_buildings
WHERE master_id = ?
`

func (q *Queries) GetSaleBuildingByMasterID(ctx context.Context, masterID string) (SaleBuilding, error) {
	row := q.db.QueryRowContext(ctx, getSaleBuildingByMasterID, masterID)
	var i SaleBuilding
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.ConstructionCost,
		&i.ConstructionTimeS,
	)
	return i, err
}

const getSaleResourcesByBuildingID = `-- name: GetSaleResourcesByBuildingID :many
SELECT sale_building_id, resource_id, price_per_unit, units_sold_per_second
FROM sale_resources
WHERE sale_building_id = ?
ORDER BY resource_id
`

func (q *Queries) GetSaleResourcesByBuildingID(ctx context.Context, saleBuildingID string) ([]SaleResource, error) {
	rows, err := q.db.QueryContext(ctx, getSaleResourcesByBuildingID, saleBuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleResource
	for rows.Next() {
		var i SaleResource
		if err := rows.Scan(
			&i.SaleBuildingID,
			&i.ResourceID,
			&i.PricePerUnit,
			&i.UnitsSoldPerSecond,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSaleBuilding = `-- name: UpsertSaleBuilding :exec
INSERT INTO sale_buildings (id, master_id, name, construction_cost, construction_time_s)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(master_id) DO UPDATE SET
  id = excluded.id,
  name = excluded.name,
  construction_cost = excluded.construction_cost,
  construction_time_s = excluded.construction_time_s
`

type UpsertSaleBuildingParams struct {
	ID                string `json:"id"`
	MasterID          string `json:"master_id"`
	Name              string `json:"name"`
	ConstructionCost  int64  `json:"construction_cost"`
	ConstructionTimeS int64  `json:"construction_time_s"`
}

func (q *Queries) UpsertSaleBuilding(ctx context.Context, arg UpsertSaleBuildingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSaleBuilding,
		arg.ID,
		arg.MasterID,
		arg.Name,
		arg.ConstructionCost,
		arg.ConstructionTimeS,
	)
	return err
}
