package db

// ProductionProcess represents a production process tied to a building.
// IDs are fixed and not autogenerated.
type ProductionProcess struct {
	ID               int64
	Name             string
	ProcessingTimeMs int64
	BuildingID       int64
	WindowStartHour  *int64
	WindowEndHour    *int64
}
