package db

// ProductionBuilding represents a production building type in the game
// with a fixed, non-autogenerated ID.
type ProductionBuilding struct {
	ID   int64
	Name string
	Cost int64
}
